### ISSUE TITLE
Memory allocation (malloc) for arrays in c language utilizing webassembly?

### ISSUE THREAD

**Issue by jmanden** [wasdk/WebAssemblyStudio#177]
New to webassembly and the c language.

I have a question regarding webassembly compiled in wasm fiddle. See script fiddle: https://wasdk.github.io/WasmFiddle/?1cmwxv

I'm trying to make the following script work where I declare the size of arrays with array sizes provided from JS code (e.g. writeArrayHelper) with the malloc function (e.g. in the getIntOffsetWriteArray0 c function) in order to allocate memory for arrays.
However, I keep getting the following errors:

Uncaught LinkError: WebAssembly Instantiation: Import #0 module="env" function="malloc" error: function import requires a callable

I have included the #include where "malloc" is supposed to be defined.

Is there another way in webassembly I need to define malloc?

Kind regards

**Comment by yurydelendik** [comment]
The malloc is defined in libc, which will be include in final wasm by linker. The old compiler in WasmFiddle does not do that (in its settings you can set a new compiler option though). Since you are trying to use memory allocation and other function that require system, you will need to implement/stub syscalls. Closing as answered.
