### ISSUE TITLE
unable to compile WebAssemblyStudio project locally on win10 - Illegal characters in file name

### ISSUE THREAD

**Issue by onelsonic** [wasdk/WebAssemblyStudio#463]
I cannot compile a project locally on win10 it says : **Illegal characters in file name**
<img width="760" alt="2020-07-18 02_03_10-WebAssembly Studio" src="https://user-images.githubusercontent.com/53947594/87839378-e32b3580-c89a-11ea-95d6-ea8100b46ef4.png">

**Comment by MaxGraey** [comment]
I guess this field for `filename` (<name>.<ext>), not for full `path`

**Comment by onelsonic** [comment]
either full path or just the file name without the path will not work on windows 10.

**Comment by MaxGraey** [comment]
it should works) WebAssembly Studio uses [virtual file system](https://github.com/wasdk/WebAssemblyStudio/blob/master/src/models/File.ts#L30) which not relate on OS at all.

**Comment by onelsonic** [comment]
well is is not working on win 10.

**Comment by nokotan** [comment]
In my win10, there seems to be no problem with file path.

![WasmStudioOnWin10](https://user-images.githubusercontent.com/20501723/93873210-4b1f5180-fd0c-11ea-86bd-6f94f8c2de92.png)

It is strange that main.c is shown as "src\\main.c" in the project view, and is not in "/src" folder. The problem is probably caused inconsistent path separater, between project view ("\") and WebAssembly Editor (expects "/").

You can manually create "/src" folder and move "main.c", "main.html", and "main.js" into that folder, then it will be compiled.

**Comment by onelsonic** [comment]
the problem occurs when building on win10 locally.
the web version as per your screenshot https://webassembly.studio/ is fine

**Comment by onelsonic** [comment]
not ideal but your workaround works :
creating the directory /src and moving and renaming the files seems to works.
You found what is causing this issue. @nokotan

**Comment by nokotan** [comment]
Your mention helped me understand this problem better, thanks.

I think this is build-time failure when processing templates projects.
[This workaround](https://github.com/nokotan/WebAssemblyStudio/commit/af5bd24be9985de85d49a9da5172d5473ad2f313) does fix this problem?

**Comment by onelsonic** [comment]
Hi @nokotan yes your code is fixing the windows build when running locally.
👍

**Comment by onelsonic** [comment]
thanks @nokotan 👍 
I'm closing this.
